export const products= [
    {
      id: 1,
      name: 'Electronics',
      image: '/assets/products/product1.png',
      alt : 'books',
      rating: 4.8,
      price : 49,
      description: 'Explore the latest gadgets and electronics.',
    },
    {
      id: 2,
      name: 'Clothing',
      image: '/assets/products/product2.png',
      alt : 'books',
      rating: 4.8,
      price : 49,
      description: 'Discover trendy fashion and clothing.',
    },
    {
      id: 3,
      name: 'Books',
      image: '/assets/products/product3.png',
      alt : 'books',
      rating: 4.8,
      price : 49,
      description: 'Find your next favorite book.',
    },
    {
        id: 4,
        name: 'Books',
        image: '/assets/products/product4.png',
        alt : 'books',
        rating: 4.8,
        price : 49,
        description: 'Find your next favorite book.',
      },
      {
        id: 5,
        name: 'Books',
        image: '/assets/products/product5.png',
        alt : 'books',
        rating: 4.8,
        price : 49,
        description: 'Find your next favorite book.',
      },
      {
        id: 6,
        name: 'Books',
        rating: 4.8,
        price : 49,
        image: '/assets/products/product6.png',
        description: 'Find your next favorite book.',
      },
      {
        id: 7,
        name: 'Books',
        image: '/assets/products/product7.png',
        alt : 'books',
        rating: 4.8,
        price : 49,
        description: 'Find your next favorite book.',
      },
      {
        id: 8,
        name: 'Books',
        image: '/assets/products/product8.png',
        alt : 'books',
        rating: 4.8,
        price : 49,
        description: 'Find your next favorite book.',
      },
]